### ISSUE TITLE
System.IO.Directory.Delete ( "path", true); throws exception FileNotFound

### ISSUE THREAD

**Issue by IvanKonov** [dokan-dev/dokan-dotnet#94] opened 2016-08-04 12:24 UTC
`System.IO.Directory.Delete ( "path", true);`
 It throws an exception FileNotFound for subdirectories , but I send that they exist

**Comment by Liryna** [comment] 2016-08-04 12:27
@IvanKonov Can you be more specific? 
Also does the behavior can be reproduce on the mirror?

**Comment by marinkobabic** [comment] 2016-08-04 12:30
@IvanKonov 
Did you try to send the STATUS_DIRECTORY_NOT_EMPTY if it has some subdirectories or files.

**Comment by IvanKonov** [comment] 2016-08-04 12:40
@Liryna Yes , on the mirror repeats
execute this code for a disk:
`        private static void DeleteDirectory()
        {
            string path_root_system = Path.GetRandomFileName();
            string path_in_dir_system = Path.GetRandomFileName();
            DriveInfo info = new DriveInfo(Test.disk_label.ToString());
            string name = info.Name;
            DirectoryInfo dir_system = new DirectoryInfo(name + path_root_system);
            dir_system.Create();
            DirectoryInfo dir_two = new DirectoryInfo(dir_system + @"\" + path_in_dir_system);
            dir_two.Create();
            System.IO.Directory.Delete(dir_system.ToString(), true);// FileNotFoundException
        }`

**Comment by IvanKonov** [comment] 2016-08-04 12:43
@marinkobabic 
yes, but I pass true System.IO.Directory.Delete ( "path", true);

**Comment by IvanKonov** [comment] 2016-08-04 13:55
it is a bug , or it should be ?

**Comment by IvanKonov** [comment] 2016-08-04 14:01
@marinkobabic 
I tried not to send STATUS_DIRECTORY_NOT_EMPTY, instead of always sending DokanResult.Success:
```
        public NtStatus DeleteDirectory(string fileName, DokanFileInfo info)
        {
            return Trace("DeleteDirectory", fileName, info, DokanResult.Success);
        }
```
but it did not help

**Comment by marinkobabic** [comment] 2016-08-04 14:10
If your code works against ntfs drive like your system c:\ drive, then it must work with dokan drive as well using the mirror application. If it does not work, then it's a bug. I'm sure Liryna will investigate the issue. What you could do is to add an additional test to the existing .net tests and make a pull request. This way we can ensure, that it will never fail again in the future.

**Comment by Liryna** [comment] 2016-08-06 08:07
@IvanKonov your code work perfectly on the C# Mirror
You should compare your code behaviour and the C#Mirror and see where is the difference
```
08/06/2016 01:05:40 - [Mirror] GetVolumeInformation('<null>', {<null>, False, False, False, False, #4, False, False}, out DOKAN, out CaseSensitiveSearch, CasePreservedNames, UnicodeOnDisk, PersistentAcls, SupportsRemoteStorage, out NTFS) -> Success
08/06/2016 01:05:40 - [Mirror] Mounted('<null>', {<null>, False, False, False, False, #0, False, False}) -> Success
08/06/2016 01:05:58 - [Mirror] CreateFile('\nibi2sls.55i', {<null>, False, False, False, False, #2564, False, False}, [ReadAttributes], [ReadWrite, Delete], [Open], [None], [0]) -> ObjectNameNotFound
08/06/2016 01:05:58 - [Mirror] CreateFile('\nibi2sls.55i', {<null>, False, False, False, False, #2564, False, False}, [ReadAttributes], [ReadWrite, Delete], [Open], [None], [0]) -> ObjectNameNotFound
08/06/2016 01:05:58 - [Mirror] CreateFile('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}, [ReadData, Synchronize], [ReadWrite], [CreateNew], [None], [Normal]) -> Success
08/06/2016 01:05:58 - [Mirror] GetFileInformation('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:58 - [Mirror] GetFileInformation('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:58 - [Mirror] Cleanup('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:58 - [Mirror] CloseFile('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:58 - [Mirror] CreateFile('\nibi2sls.55i\ax2hytme.vao', {<null>, False, False, False, False, #2564, False, False}, [ReadAttributes], [ReadWrite, Delete], [Open], [None], [0]) -> ObjectNameNotFound
08/06/2016 01:05:58 - [Mirror] CreateFile('\nibi2sls.55i\ax2hytme.vao', {<null>, False, False, False, False, #2564, False, False}, [ReadAttributes], [ReadWrite, Delete], [Open], [None], [0]) -> ObjectNameNotFound
08/06/2016 01:05:58 - [Mirror] CreateFile('\nibi2sls.55i', {System.Object, False, True, False, False, #2564, False, False}, [ReadAttributes], [ReadWrite, Delete], [Open], [None], [0]) -> Success
08/06/2016 01:05:58 - [Mirror] GetFileInformation('\nibi2sls.55i', {System.Object, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:58 - [Mirror] GetFileInformation('\nibi2sls.55i', {System.Object, False, True, False, False, #2564, False, False}) -> Success
Cleanup('\nibi2sls.55i', {System.Object, False, True, False, False, #2564, False, False} - entering
08/06/2016 01:05:58 - [Mirror] Cleanup('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:58 - [Mirror] CloseFile('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:58 - [Mirror] CreateFile('\nibi2sls.55i\ax2hytme.vao', {<null>, False, True, False, False, #2564, False, False}, [ReadData, Synchronize], [ReadWrite], [CreateNew], [None], [Normal]) -> Success
08/06/2016 01:05:58 - [Mirror] GetFileInformation('\nibi2sls.55i\ax2hytme.vao', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:58 - [Mirror] Cleanup('\nibi2sls.55i\ax2hytme.vao', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:58 - [Mirror] CloseFile('\nibi2sls.55i\ax2hytme.vao', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:58 - [Mirror] CreateFile('\nibi2sls.55i', {System.Object, False, True, False, False, #2564, False, False}, [ReadAttributes], [ReadWrite, Delete], [Open], [None], [0]) -> Success
08/06/2016 01:05:58 - [Mirror] GetFileInformation('\nibi2sls.55i', {System.Object, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:58 - [Mirror] GetFileInformation('\nibi2sls.55i', {System.Object, False, True, False, False, #2564, False, False}) -> Success
Cleanup('\nibi2sls.55i', {System.Object, False, True, False, False, #2564, False, False} - entering
08/06/2016 01:05:58 - [Mirror] Cleanup('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:58 - [Mirror] CloseFile('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:58 - [Mirror] CreateFile('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}, [ReadData, Synchronize], [ReadWrite, Delete], [Open], [None], [0]) -> Success
08/06/2016 01:05:58 - [Mirror] GetFileInformation('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:59 - [Mirror] FindFilesWithPattern('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:59 - [Mirror] CreateFile('\nibi2sls.55i\ax2hytme.vao', {<null>, False, True, False, False, #2564, False, False}, [ReadData, Synchronize], [ReadWrite, Delete], [Open], [None], [0]) -> Success
08/06/2016 01:05:59 - [Mirror] GetFileInformation('\nibi2sls.55i\ax2hytme.vao', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:59 - [Mirror] FindFilesWithPattern('\nibi2sls.55i\ax2hytme.vao', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:59 - [Mirror] Cleanup('\nibi2sls.55i\ax2hytme.vao', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:59 - [Mirror] CloseFile('\nibi2sls.55i\ax2hytme.vao', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:59 - [Mirror] CreateFile('\nibi2sls.55i\ax2hytme.vao', {<null>, False, True, False, False, #2564, False, False}, [ReadAttributes, Delete, Synchronize], [ReadWrite, Delete], [Open], [None], [0]) -> Success
08/06/2016 01:05:59 - [Mirror] GetFileInformation('\nibi2sls.55i\ax2hytme.vao', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:59 - [Mirror] GetFileInformation('\nibi2sls.55i\ax2hytme.vao', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:59 - [Mirror] GetFileInformation('\nibi2sls.55i\ax2hytme.vao', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:05:59 - [Mirror] DeleteDirectory('\nibi2sls.55i\ax2hytme.vao', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:06:01 - [Mirror] Cleanup('\nibi2sls.55i\ax2hytme.vao', {<null>, True, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:06:01 - [Mirror] CloseFile('\nibi2sls.55i\ax2hytme.vao', {<null>, True, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:06:01 - [Mirror] Cleanup('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:06:01 - [Mirror] CloseFile('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:06:01 - [Mirror] CreateFile('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}, [ReadAttributes, Delete, Synchronize], [ReadWrite, Delete], [Open], [None], [0]) -> Success
08/06/2016 01:06:01 - [Mirror] GetFileInformation('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:06:01 - [Mirror] GetFileInformation('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:06:01 - [Mirror] GetFileInformation('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:06:01 - [Mirror] DeleteDirectory('\nibi2sls.55i', {<null>, False, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:06:01 - [Mirror] Cleanup('\nibi2sls.55i', {<null>, True, True, False, False, #2564, False, False}) -> Success
08/06/2016 01:06:01 - [Mirror] CloseFile('\nibi2sls.55i', {<null>, True, True, False, False, #2564, False, False}) -> Success
```

**Comment by IvanKonov** [comment] 2016-08-08 12:29
I'm using version 1.08 , and I have the following code into the mirror does not work (see screenshot )
![default](https://cloud.githubusercontent.com/assets/20556427/17479698/aa1550ec-5d7c-11e6-935e-b55daae3a147.PNG)

**Comment by IvanKonov** [comment] 2016-08-08 12:32
above the 1.08 version can not install the driver , he says that he is not signed

**Comment by Liryna** [comment] 2016-08-08 12:35
Are you using Win7 ? can you update it ?
My test was on 1.0.0

**Comment by IvanKonov** [comment] 2016-08-08 12:42
I use windows7 profesional sp1, and am unable to update this corporate computer

**Comment by Liryna** [comment] 2016-08-08 12:42
Ok, can you move to Dokan 1.0.0-rc4 with dokan-dotnet 1.1.0.0-rc4 ?

**Comment by IvanKonov** [comment] 2016-08-08 12:52
It is impossible to run dokany 1.0.0-RC4 since He writes that the driver is not signed . Normal startup only 0.8 .

**Comment by Liryna** [comment] 2016-08-08 12:57
Ok I see, there is probably not the KB3033929 installed on the Win7 or the root certificat is missing from your windows (also a missing update).
This is related to Windows SHA2 restriction since january 2016.

I don't know what to propose, this behavior can only be fixed with 1.0.0 Dokan.

**Comment by IvanKonov** [comment] 2016-08-08 13:01
Yes, I understand that you have already fixed this bug in older versions . Please tell me whether the release is expected with signed drivers as well as in 0.8 ?

**Comment by Liryna** [comment] 2016-08-08 14:17
@IvanKonov The RC is correctly signed. There is no changes that will be made. The system of your company need to be updated and root certificate from godaddy sha2 need to be added. 

It is Microsoft that force signed binary after 1 January 2016 to be signed with Sha2 certificate. We can do nothing about it :(

**Comment by IvanKonov** [comment] 2016-08-08 14:33
OK, I understand , thank you very much for your help. I will think how to upgrade windows, and go to the 1.0.0+  :)

**Closed** 2016-08-15 09:06 UTC
Labels: question
