### ISSUE TITLE
DeleteOnClose flag

### ISSUE THREAD

**Issue by js69** [dokan-dev/dokan-dotnet#83] opened 2016-06-13 09:42 UTC
Hi Liryna,

I have some issue with regards to the DeleteOnClose flag. This was apparently fixed at driver level here: https://github.com/dokan-dev/dokany/issues/18

My app though still fails to delete files that were opened with "Delete On Close" flag. 

This is the procmon log for Excel 2010 on a normal NTFS drive, when opening 4.xlsx the temporay file ~$4.xlsx will be openend. It will be closed and deleted when Excel is closed.

- 10:25:04,6877324	EXCEL.EXE	8820	CreateFile	C:\test\~$4.xlsx	 SUCCESS	Desired Access: Generic Read/Write, Delete, Disposition: Create, Options: Synchronous IO Non-Alert, Non-Directory File, Delete On Close, Open No Recall, Attributes: H, ShareMode: Read, AllocationSize: 0, OpenResult: Created
- 10:25:04,6880769	EXCEL.EXE	8820	CreateFile	C:\test\~$4.xlsx	 SUCCESS	Desired Access: Write Attributes, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
- 10:25:04,6881516	EXCEL.EXE	8820	SetBasicInformationFile	C:\test\~$4.xlsx	SUCCESS	CreationTime: 01.01.1601 02:00:00, LastAccessTime: 01.01.1601 02:00:00, LastWriteTime: 01.01.1601 02:00:00, ChangeTime: 01.01.1601 02:00:00, FileAttributes: HNNCI
- 10:25:04,6881965	EXCEL.EXE	8820	CloseFile	C:\test\~$4.xlsx 	SUCCESS
- 10:25:04,6882500	EXCEL.EXE	8820	WriteFile	C:\test\~$4.xlsx	 SUCCESS Offset: 0, Length: 55, Priority: Normal
- 10:25:04,6883144	EXCEL.EXE	8820	WriteFile	C:\test\~$4.xlsx	 SUCCESS	Offset: 55, Length: 110, Priority: Normal
- 10:25:04,6883339	EXCEL.EXE	8820	FlushBuffersFile	C:\test\~$4.xlsx	 SUCCESS
- 10:25:04,6883696	EXCEL.EXE	8820	WriteFile	C:\test\~$4.xlsx 	SUCCESS	Offset: 0, Length: 4.096, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
- 10:25:29,0750834	EXCEL.EXE	8820	CloseFile	C:\test\~$4.xlsx	 SUCCESS

I have noticed that in ZwCreateFileProxy if the fileOptions.DeleteOnClose is set,  rawFileInfo.DeleteOnClose is still false.

Cleanup and Close for the file in my app's drive are never called with DeleteOnClose=true which I would expect should happen.

The DokanNet mirror still does it correctly though. I see this in the log when Excel is closed:

- 06/13/2016 11:21:04 - [Mirror] CreateFile('\test\~$4.xlsx', {<null>, DeleteOnClose=False, False, False, False, #948, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [0]) -> ObjectNameNotFound
- 06/13/2016 11:21:04 - [Mirror] CloseFile('\test\~$4.xlsx', {<null>, DeleteOnClose=False, False, False, False, #6772, False, False}) -> Success

The code in Cleanup "if (info.DeleteOnClose)" is never executed, the mirror FileStream for "~$4.xlsx" is apparently only deleted on Close because it was created with relayed FileOptions.

Shouldn't the DeleteOnClose flag be set on Close/Cleanup by DokanNet in these cases?

**Comment by Liryna** [comment] 2016-06-13 11:12
Hi @js69 ,

On my side Delete On Close is correctly set otherwise the C# Mirror would never been able to remove files.

Having the flag in Close is useless because in Windows logic, the file has to be delete in the Cleanup.

Have you been able to make a simple test that delete a file ? To see if this only happen with Excel or in every cases ?

Be aware to https://github.com/dokan-dev/dokany/issues/249, is it is the same behaviour that you face, it is probably an issue directly in Dokan and not in the C#.

**Comment by js69** [comment] 2016-06-13 11:38
The C# mirror does not handle the DeleteOnClose case itself at all - that is done by Windows for the FileStream you create. The same is probably true for the C mirror sample.

The Cleanup never receives a DeleteOnClose=true flag from any Office application, as far as I can tell.

This might be fixable in the driver if it were to remember the FILE_DELETE_ON_CLOSE flag set on Create. In any case, Cleanup needs to have that flag sent to allow it to handle the case correctly.

**Comment by Liryna** [comment] 2016-06-13 11:47
What you describe is already made https://github.com/dokan-dev/dokany/commit/770d2a76a97f7cf86002660d44c9aaeba8f474f0#diff-f8956c408fab8dbdc1c6ccfbd0a1035cR108

We save the `FILE_DELETE_ON_CLOSE` and set it in the Cleanup. 

In the C# Mirror logs that you gave, DeleteOnClose is not set during CreateFile.
I see in your logs that there is two CreateFile and one with DeleteOnClose but are you sure that there is no DeleteOnClose flag set ?

DeleteOnClose directly come from `dokan.dll` and the flag is set here https://github.com/dokan-dev/dokany/blob/7c53ac77393e1430ad228b2e514f1f4a5d7fd247/dokan/dokan.c#L543

BUT there is probably something with Office 2010 and the magic of Windows that we do not handle.
I only think that if you see the request CreateFile with the flag delete, it have to be also set in Cleanup.

**Comment by js69** [comment] 2016-06-13 12:30
I don't see in the Dokan driver cleanup.c anything that handles the Delete On Close flag.

Shouldn't there be something similar like what was added in create.c?

    if (irpSp->Parameters.Create.Options & FILE_DELETE_ON_CLOSE) {
      fcb->Flags |= DOKAN_DELETE_ON_CLOSE;

**Comment by Liryna** [comment] 2016-06-13 12:58
In the kernel side, we only have the information during the Create. Therefore, we save the flag in `fcb->Flags` https://github.com/dokan-dev/dokany/commit/770d2a76a97f7cf86002660d44c9aaeba8f474f0#diff-86caa6b16e4044982075fe5d5bc59915R514
and we set it back in Cleanup event https://github.com/dokan-dev/dokany/commit/770d2a76a97f7cf86002660d44c9aaeba8f474f0#diff-f8956c408fab8dbdc1c6ccfbd0a1035cR108

**Comment by js69** [comment] 2016-06-16 12:42
OK, getting back to the issue: 
info.DeleteOnClose is never true in in the C' mirror Cleanup when opening and closing a file in Excel 2010 or Excel 2016. Could you please trace if that flag is really correctly set in the driver code's Cleanup?

**Comment by Liryna** [comment] 2016-06-17 08:55
@js69 , I will take a look this weekend !
Just to be sure, does the behaviour also happen with Excel 2016 with C mirror ?

**Comment by Liryna** [comment] 2016-06-19 14:34
Hi @js69 ,

From my observation (office 2016), the flag is correctly set during the CreateFile BUT during the Cleanup, the flag is not set.
The C and C# mirror succeed to delete the temporary file because they open the flag with DeleteOnClose during the CreateFile.

I agree that Cleanup should send the DeleteOnClose flag but I have no idea why does the `fcb->Flags;` does not have the correctly value set from CreateFile.

Also the Context is seems to be correctly set so it is strang that flag is not correctly restored.
@marinkobabic Do you have any idea why this would happen in some cases (only have been to reproduce with office) ?

```
[DokanFS] ==> DokanCreate
[DokanFS]   ProcessId 3864
[DokanFS]   FileName:\liryna\Desktop\~$hey.xlsx
[DokanFS]    IdType = VCB
[DokanFS]   IrpSp->Flags = 0
[DokanFS]   Allocate FCB
[DokanFS]   FILE_DELETE_ON_CLOSE is set so remember for delete in cleanup
[DokanFS] FLAGS VALUE = 16
```

**Comment by marinkobabic** [comment] 2016-06-20 10:48
It's clear to me what happens:

1. CreateFile "myfile" + DELETE_ON_CLOSE
2. CreateFile "myfile + OPEN_EXISTING
3. CloseFile "myfile"
4. CloseFile "myfile

If the order is like above, the CleanUp will not set the flag DeleteOnClose. Here the code causing the problem

https://github.com/dokan-dev/dokany/blob/master/sys/create.c#L591-L597
It's the https://github.com/dokan-dev/dokany/blob/master/sys/create.c#L596 which removes the flag during the second create. To fix this bug, the else line should be removed.

So but now you will get the flag during both CleanUp which may be wrong (example above 3,4). So after this line here https://github.com/dokan-dev/dokany/blob/master/sys/cleanup.c#L106 we need to check if the fcb->FileCount > 1 and if the flag DOKAN_DELETE_ON_CLOSE is set. If this is true, the flag should be removed from eventContext->FileFlags.

Hope you agree :smile:

**Comment by Liryna** [comment] 2016-06-20 10:56
:tada: Yeah @marinkobabic , it is exactly what is happening! that's sounds like a good fix :smiley: 

But is it not possible to have a personnalized flag for each request ? because with your fix, it is always the last cleanup that get the delete on close.

**Comment by marinkobabic** [comment] 2016-06-20 15:39
@Liryna

 

This makes also sense. Only if there is no handle on the file, the file should be removed. 

 

Thanks

Marinko

 

Von: Liryna [mailto:notifications@github.com] 
Gesendet: Montag, 20. Juni 2016 12:57
An: dokan-dev/dokan-dotnet <dokan-dotnet@noreply.github.com>
Cc: Babic Marinko <marinko.babic@ruf.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [dokan-dev/dokan-dotnet] DeleteOnClose flag (#83)

 

🎉 Yeah @marinkobabic <https://github.com/marinkobabic>  , it is exactly what is happening! that's sounds like a good fix 😃 

But is it not possible to have a personnalized flag for each request ? because with your fix, it is always the last cleanup that get the delete on close.

**Comment by marinkobabic** [comment] 2016-06-20 16:20
When the information is on CCB then it should be a personalized information. The question is when does windows delete the file? 

CreateFile
CreateFile + DELETE_ON_CLOSE
CloseFile above

Wait 30 Seconds
CloseFile using the handle of the first create.

If the file is closed after the wait, the the fix is fine. If the file is removed before the wait, then we should put the flag on CCB.

**Comment by Liryna** [comment] 2016-06-20 18:34
I made some test in current status of dokan:
```
(1) CreateFile
(2) CreateFile + DELETE_ON_CLOSE
(2) CloseFile - Delete flag // DeleteFile ERROR_ACCESS_DENIED
(1) CloseFile - Delete flag
```
```
(1) CreateFile + DELETE_ON_CLOSE
(2) CreateFile
(2) CloseFile - No Delete flag
(1) CloseFile - No Delete flag
```
With this commit:https://github.com/dokan-dev/dokany/commit/f57b054b8d967573ef78e7f1164dfe994f1a9c43
```
(1) CreateFile
(2) CreateFile + DELETE_ON_CLOSE
(2) CloseFile - Delete flag // DeleteFile ERROR_ACCESS_DENIED
(1) CloseFile
```
```
(1) CreateFile + DELETE_ON_CLOSE
(2) CreateFile
(2) CloseFile
(1) CloseFile - Delete flag
```
So your idea @marinkobabic to put on CCB since to be the good one ! :+1: 

Before adding it to master branch, I just would like to know if https://github.com/dokan-dev/dokany/blob/master/sys/create.c#L596 is really needed and what is the purpose of it ? (it seems like the flag on fcb is used for `DeletePending`)

**Comment by marinkobabic** [comment] 2016-06-20 18:44
Hi Liryna

The line makes no sense, so you can remove it. Good job!

Thanks
Marinko


Von Samsung Mobile gesendet

**Comment by Liryna** [comment] 2016-06-20 18:53
Ok great !

Thank you for you expertise @marinkobabic  :smiley: and @js69 for your report ! It was hard to see :)

Fixed on master with https://github.com/dokan-dev/dokany/commit/59d08ffca07f69c40d9d46e5a687816cb72d0a49

**Closed by Liryna** 2016-06-20 18:53 UTC
